### ISSUE TITLE
SideShift.ai implementation has hardcoded affiliate ID

### ISSUE THREAD

**Issue by WizardOfCodez** [btcpayserver/btcpayserver-plugins#29]
I am using BTCPayServer on many of my projects. While plowing through your BTCPay Plugins Repo (https://github.com/Kukks/btcpayserver/tree/plugins/collection/Plugins) I recognized that the Affiliate-ID for the Sideshift.ai Plugin is hardcoded (probably one of the devs I guess) so it isn’t possible to change it which I would like to do.

Since there is no documentation on adding a custom plugin to BTCPayServer: Would it be possible to add a configuration option? The VueComponent here (https://github.com/Kukks/btcpayserver/blob/plugins/collection/Plugins/BTCPayServer.Plugins.SideShift/Resources/js/sideShiftComponent.js) should need an additional prop that could be fed through the BTCPayServer Plugin configuration page.

**Comment by Kukks** [comment]
I maintain these plugins personally. I've integrated 3 or 4 variants of these services into BTCPay Server over the years, and they always break and need regular maintenance. The only motivation I have to keep maintaining these is the affiliate revenue so I will not be adding this feature.  PS, these integrations don't generate big amounts of $$$ as #33 thinks.  

With that said, the code is open source. So feel free to fork and change as needed but do consider that that reduces my incentive to work more on these. 

Hope you understand :)

**Comment by WizardOfCodez** [comment]
This is completely understandable to me. The thing that puts a grain of salt in it is that there was no statement about this in any doc and that you only came up with it when we actively asked for it and waited 2 months.

Also, you know that there is a huge difference between "open source" and "easy to implement". Creating a BTCPay plugin is nowhere documented and even if someone is willing to build it on his own there is no way to add it to our own BTCPay instance because of the "shop-like" interface and no available documentation.

No personal critiques on you, but it lays a shadow on a good project which aims to support decentralized adoption through BTC but then benefits the devs through a backdoor without any option to change it.

**Comment by Kukks** [comment]
Sorry about the long response time,  but I'm always working on ten things
at once and things slip away.  I only noticed because I was assigned and
managed to catch the duplicate issue comment notification.

Plugins haven't really been polished off enough to advertise as something
someone can easily build.  Right now it's only two of us who are working on
getting some plugins out there and fine-tuning things as we go along, but
it does require intricate knowledge of how stuff works. With that said,  if
anyone actually asked for details on how to build plugins we would Def help
and would probably use that as a starting point to documenting that side of
things.

Anything built as a plugin is unofficial.

PS, you can upload plugins through the manual upload form at the bottom.
You can also switch which repo the plugin list loads from when configuring
btcpayserver.

**Comment by dennisreimann** [comment]
> With that said,  if anyone actually asked for details on how to build plugins we would Def help and would probably use that as a starting point to documenting that side of things.

I've started a documentation page, but have put this aside with the recent plans to maybe change how plugins might be built. See btcpayserver/btcpayserver#3961

As @Kukks said it is very early and we are still trying to find good ways to easily build plugins, but currently things are still changing, so it'd send a false signal to document it and open it up.

**Comment by bobget** [comment]
Thanks for replying. If these plugins require maintenance regularly and it is you incentive to keep maintaining them I'm fine with the decision not to change that.
thank you for making and maintaining those plugins
